ARG APP_DIR="/app"

FROM node:21-alpine as builder

WORKDIR ${APP_DIR}
COPY package*.json .
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:stable-alpine3.17-slim
EXPOSE 80
WORKDIR /usr/share/nginx/html
RUN rm -rf * && ln -sf . static
COPY --from=builder ${APP_DIR}/build/* .
